/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
/**
 *
 * @author USUARIO
 */
public class MenuTipoPartida extends javax.swing.JFrame {

    /**
     * Creates new form MenuTipoPartida
     */
    public MenuTipoPartida() {
        initComponents();
        setTitle("The Elemental War");
        setSize(916, 639);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        rapida = new javax.swing.JButton();
        normal = new javax.swing.JButton();
        avanzada = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Seleccione el Tipo de Partida:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 70, 530, 70);

        rapida.setBackground(new java.awt.Color(0, 29, 61));
        rapida.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rapida.setForeground(new java.awt.Color(255, 255, 0));
        rapida.setText("Partida Rápida");
        rapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapidaActionPerformed(evt);
            }
        });
        getContentPane().add(rapida);
        rapida.setBounds(300, 220, 340, 70);

        normal.setBackground(new java.awt.Color(0, 29, 61));
        normal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        normal.setForeground(new java.awt.Color(255, 255, 0));
        normal.setText("Partida Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        getContentPane().add(normal);
        normal.setBounds(300, 310, 340, 70);

        avanzada.setBackground(new java.awt.Color(0, 29, 61));
        avanzada.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        avanzada.setForeground(new java.awt.Color(255, 255, 0));
        avanzada.setText("Partida Avanzada");
        avanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzadaActionPerformed(evt);
            }
        });
        getContentPane().add(avanzada);
        avanzada.setBounds(300, 400, 340, 70);

        jButton4.setText("jButton1");
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 250, 73, 23);

        regresar.setBackground(new java.awt.Color(164, 19, 60));
        regresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(760, 530, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programita/fondoMenuTipoPartida.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>                        

    private void rapidaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Random rand = new Random();
        new Campo(rand.nextInt(3) + 10);
        setVisible(false);
    }                                      

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Random rand = new Random();
        new Campo(rand.nextInt(2) + 13);
        setVisible(false);
    }                                      

    private void avanzadaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Random rand = new Random();
        new Campo(rand.nextInt(2) + 15);
        setVisible(false);
    }                                        

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new MenuGeneral();
        setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTipoPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTipoPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTipoPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTipoPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTipoPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton avanzada;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton normal;
    private javax.swing.JButton rapida;
    private javax.swing.JButton regresar;
    // End of variables declaration                   
}
